version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    groups:
      allNonMajor:
        update-types:
          - 'minor'
          - 'patch'
      typescriptEslintMajor:
        update-types:
          - 'major'
        patterns:
          - '@typescript-eslint/*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
